### PR TITLE
Removal of ios VR functionality

### PR DESCRIPTION
**Pull request by HedwigAR**

### CODE REVIEW

**Comment by HedwigAR** [comment]
Seems like a whole lot of files got included that weren't there before, will look into that.

**Comment by HedwigAR** [comment]
the majority of the added lines seem to be .mlmodelc files (which in turn are related to machine learning). These are generated by virokit but don't seem to be necessary for this actual project, project still runs without them.

**Comment by dthian** [comment]
Awesome job @HedwigAR, could you create a Pull request for the viromedia/viro repo as well? Once the builds are successful there I'll merge it right in. Thanks!

**Comment by Danik711** [comment]
Thank you very much @HedwigAR for doing this!!!! Can youp lease tell me where can I pull the new version?

**Comment by smarki** [comment]
Hey @Danik711 and @dthian, while the change removes the gvrsdk library, it also removes Viro static headset functionality, rendering a major part of Viro functionality unusable on iOS devices. 

We are not planning on putting any effort into reimplementing it at the current time, therefore we are not considering PR'ring the changes back to viromendia/viro at the current time.

Of course @Danik711, you are free to build it yourself and use it for your own use-case, as is. We are not planning on releasing it.

**Comment by Danik711** [comment]
Hey @smarki, I am quite new to the react-native and git community. I cant find you fixes or I am just blind. Can you please tell me where I can get your version without gvrsdk?

Thank you in advance!

**Comment by ranjanpoudel1234** [comment]
Hi @smarki , @HedwigAR , have you guys made a version of react-viro with this fix somewhere that we can use ?

**Comment by costerik** [comment]
Hey guys, I'm receiving this error on Android when I run `npx react-native run-android`

```
* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-viro.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-viro:
          - None of the consumable configurations have attributes.
```

Any advice?
Thanks!

**Comment by smarki** [comment]
@ranjanpoudel1234 We aren't releasing these versions anywhere. We also not plan on providing support for external users atm. You can look at https://github.com/ViroCommunity/viro for official support. 

But some hight level steps:
- Install viro by pointing to this repo
- For Android modify your gradle files to include the projects required by viro.
- For iOS modify your podfile to include the required libraries. 
- Happy dev flow there after if all works. 

@costerik most likely don't have the android dependencies linked; viro is not auto linkable.

**Comment by costerik** [comment]
hey @smarki thanks for your answer,

I followed these steps in order to integrate `react-viro` to an existing `react-native` project.

- `npx react-native init SampleProject --version 0.61.5`
- `yarn add https://github.com/mendix/viro.git`

After that, I made the next changes
- `android/app/build.gradle`
```
def enableHermes = project.ext.react.get("enableHermes", false);

 android {
-    compileSdkVersion rootProject.ext.compileSdkVersion
+    compileSdkVersion 28
+    flavorDimensions "platform"

     compileOptions {
         sourceCompatibility JavaVersion.VERSION_1_8
@@ -129,8 +130,9 @@ android {

     defaultConfig {
         applicationId "com.virosixtyonepointfive"
-        minSdkVersion rootProject.ext.minSdkVersion
-        targetSdkVersion rootProject.ext.targetSdkVersion
+        minSdkVersion 23
+        targetSdkVersion 28
+        multiDexEnabled true
         versionCode 1
         versionName "1.0"
     }
@@ -150,6 +152,21 @@ android {
             keyPassword 'android'
         }
     }
+    productFlavors {
+        ar {
+            resValue 'string', 'app_name', 'ViroSample-ar'
+            buildConfigField 'String', 'VR_PLATFORM', '"GVR"' //default to GVR
+        }
+        gvr {
+            resValue 'string', 'app_name', 'ViroSample-gvr'
+            buildConfigField 'String', 'VR_PLATFORM', '"GVR"'
+        }
+        ovr {
+            resValue 'string', 'app_name', 'ViroSample-ovr'
+            applicationIdSuffix '.ovr'
+            buildConfigField 'String', 'VR_PLATFORM', '"OVR_MOBILE"'
+        }
+    }
     buildTypes {
         debug {
             signingConfig signingConfigs.debug
@@ -180,7 +197,19 @@ android {

 dependencies {
     implementation fileTree(dir: "libs", include: ["*.jar"])
+    implementation 'com.android.support:appcompat-v7:28.0.0'
     implementation "com.facebook.react:react-native:+"  // From node_modules
+    implementation project(':arcore_client') // remove this if AR not required
+    implementation project(':gvr_common')
+    implementation project(path: ':viro_renderer')
+    implementation project(path: ':react_viro')
+    implementation 'com.google.android.exoplayer:exoplayer:2.7.1'
+    implementation 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'
+    implementation 'com.amazonaws:aws-android-sdk-core:2.7.7'
+    implementation 'com.amazonaws:aws-android-sdk-ddb:2.7.7'
+    implementation 'com.amazonaws:aws-android-sdk-ddb-mapper:2.7.7'
+    implementation 'com.amazonaws:aws-android-sdk-cognito:2.7.7'
+    implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.7.7'
```
- `AndroidManifest.xml`
```
<uses-permission android:name="android.permission.INTERNET" />
+    <uses-permission android:name="android.permission.CAMERA" />

     <application
       android:name=".MainApplication"
@@ -9,18 +10,21 @@
       android:icon="@mipmap/ic_launcher"
       android:roundIcon="@mipmap/ic_launcher_round"
       android:allowBackup="false"
+        android:usesCleartextTraffic="true"
       android:theme="@style/AppTheme">
       <activity
         android:name=".MainActivity"
         android:label="@string/app_name"
-        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
+        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
         android:windowSoftInputMode="adjustResize">
         <intent-filter>
             <action android:name="android.intent.action.MAIN" />
             <category android:name="android.intent.category.LAUNCHER" />
+            <category android:name="com.google.intent.category.CARDBOARD" />
         </intent-filter>
       </activity>
       <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
+        <meta-data android:name="com.google.ar.core" android:value="optional" />
     </application>
```
- `MainApplication.java`
```
 import com.facebook.soloader.SoLoader;
 import java.lang.reflect.InvocationTargetException;
 import java.util.List;
+import com.viromedia.bridge.ReactViroPackage;

 public class MainApplication extends Application implements ReactApplication {

@@ -25,6 +26,7 @@ public class MainApplication extends Application implements ReactApplication {
           List<ReactPackage> packages = new PackageList(this).getPackages();
           // Packages that cannot be autolinked yet can be added manually here, for example:
           // packages.add(new MyReactNativePackage());
+            packages.add(new ReactViroPackage(ReactViroPackage.ViroPlatform.valueOf(BuildConfig.VR_PLATFORM)));
           return packages;
         }
```
- `android/build.gradle`
```
buildscript {
-    ext {
+    /*ext {
         buildToolsVersion = "28.0.3"
         minSdkVersion = 16
         compileSdkVersion = 28
         targetSdkVersion = 28
-    }
+    }*/
     repositories {
         google()
         jcenter()
@@ -20,8 +20,16 @@ buildscript {
 }

 allprojects {
+    configurations.matching { it.name == '_internal_aapt2_binary' }.all { config ->
+        config.resolutionStrategy.eachDependency { details ->
+            details.useVersion("3.5.0-alpha03-5252756")
+        }
+    }
     repositories {
         mavenLocal()
+        maven {
+            url 'https://maven.google.com/'
+        }
```
- `android/settings.gradle`
```
rootProject.name = 'ViroSixtyOnePointFive'
 apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
-include ':app'
+include ':react_viro', ':arcore_client', ':gvr_common', ':viro_renderer'
+project(':arcore_client').projectDir = new File('../node_modules/react-viro/android/arcore_client')
+project(':gvr_common').projectDir = new File('../node_modules/react-viro/android/gvr_common')
+project(':viro_renderer').projectDir = new File('../node_modules/react-viro/android/viro_renderer')
+project(':react_viro').projectDir = new File('../node_modules/react-viro/android/react_viro')
+include ':app'
```

When I run the command `npx react-native run-android` throws this error
```
error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'. Some candidates are: 'installArDebug', 'installGvrDebug', 'installOvrDebug'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:13)
    at runOnAllDevices (/Users/erikahumada/Desktop/ViroSixtyOnePointFive/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/erikahumada/Desktop/ViroSixtyOnePointFive/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at then.result (/Users/erikahumada/Desktop/ViroSixtyOnePointFive/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

If I run the command `react-native run-android --variant=gvrDebug` throws this error.
```
Error: Command failed: ./gradlew app:installGvrDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preGvrDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:gvrDebugRuntimeClasspath'.
   > Could not resolve project :react-viro.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-viro:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:13)
    at runOnAllDevices (/Users/erikahumada/Desktop/ViroSixtyOnePointFive/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/erikahumada/Desktop/ViroSixtyOnePointFive/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at then.result (/Users/erikahumada/Desktop/ViroSixtyOnePointFive/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is the status on Android Studio after run `Clean Project` 
Screen Shot 2020-12-04 at 1 34 44 PM

but when I try to run it via android studio throws this error:
Screen Shot 2020-12-04 at 1 39 58 PM

My setup
```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.10 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.2 - ~/.nvm/versions/node/v10.15.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 23.0.1, 24.0.1, 25.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.3, 29.0.1, 29.0.2, 29.0.3, 30.0.1, 30.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Did I miss something? Could you give me a hand with this, please?

Thanks!

**Comment by wenge8n** [comment]
Hi @costerik 
did you find answer?

**Comment by costerik** [comment]
> Hi @costerik
> did you find answer?

Apparently, this project works https://github.com/ViroCommunity

**Pull request merged**
